version: '3'

services:
  nginx3:
    build: .
    labels:
      - "traefik.backend=nginx3"
      - "traefik.frontend.rule=Host:ng03.docker.localhost"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"
