version: '3'

services:
  nginx3:
    image: nginx
    labels:
      - "traefik.backend=nginx3"
      - "traefik.frontend.rule=Host:ng03.docker.localhost"
      - "traefik.port=80"
      - "traefix.port=443"
      - "traefik.frontend.entryPoints=http"
