version: '3'

services:
  nginx1:
    build: .
    labels:
      - "traefik.backend=nginx1"
      - "traefik.frontend.rule=Host:ng01.docker.localhost"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"
