version: '3'

services:
  nginx2:
    build: .
    labels:
      - "traefik.backend=nginx2"
      - "traefik.frontend.rule=Host:ng02.docker.localhost"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"
